FEATURE_NAMES = [
    "name",                 # 0
    "flow_id",              # 1
    "source_ip",            # 2
    "source_port",          # 3
    "destination_ip",       # 4
    "destination_port",     # 5
    "protocol",             # 6
    "timestamp",            # 7
    "flow_duration",        # 8
    "ttl_fwd_pkts",         # 9
    "ttl_bwd_pkts",         # 10
    "ttl_len_of_fwd_pkts",  # 11
    "ttl_len_of_bwd_pkts",  # 12
    "fwd_pkt_len_max",      # 13
    "fwd_pkt_len_min",      # 14
    "fwd_pkt_len_mean",     # 15
    "fwd_pkt_len_std",      # 16
    "bwd_pkt_len_max",      # 17
    "bwd_pkt_len_min",      # 18
    "bwd_pkt_len_mean",     # 19
    "bwd_pkt_len_std",      # 20
    "flow_bytes_per_s",     # 21
    "flow_pkts_per_s",      # 22
    "flow_iat_mean",        # 23
    "flow_iat_std",         # 24
    "flow_iat_max",         # 25
    "flow_iat_min",         # 26
    "fwd_iat_ttl",          # 27
    "fwd_iat_mean",         # 28
    "fwd_iat_std",          # 29
    "fwd_iat_max",          # 30
    "fwd_iat_min",          # 31
    "bwd_iat_ttl",          # 32
    "bwd_iat_mean",         # 33
    "bwd_iat_std",          # 34
    "bwd_iat_max",          # 35
    "bwd_iat_min",          # 36
    "fwd_psh_flags",        # 37
    "bwd_psh_flags",        # 38
    "fwd_urg_flags",        # 39
    "bwd_urg_flags",        # 40
    "fwd_header_len",       # 41
    "bwd_header_len",       # 42
    "fwd_pkts_per_s",       # 43
    "bwd_pkts_per_s",       # 44
    "min_pkt_len",          # 45
    "max_pkt_len",          # 46
    "pkt_len_mean",         # 47
    "pkt_len_std",          # 48
    "pkt_len_variance",     # 49
    "fin_flag_count",       # 50
    "syn_flag_count",       # 51
    "rst_flag_count",       # 52
    "psh_flag_count",       # 53
    "ack_flag_count",       # 54
    "urg_flag_count",       # 55
    "cwe_flag_count",       # 56
    "ece_flag_count",       # 57
    "down_to_up_ratio",     # 58
    "average_pkt_size",     # 59
    "avg_fwd_segment_size", # 60
    "avg_bwd_segment_size", # 61
    "fwd_header_len1",      # 62
    "fwd_avg_bytes_per_bulk",  # 63
    "fwd_avg_pkts_per_bulk",   # 64
    "fwd_avg_bulk_rate",       # 65
    "bwd_avg_bytes_per_bulk",  # 66
    "bwd_avg_pkts_per_bulk",   # 67
    "bwd_avg_bulk_rate",       # 68
    "subflow_fwd_pkts",        # 69
    "subflow_fwd_bytes",       # 70
    "subflow_bwd_pkts",        # 71
    "subflow_bwd_bytes",       # 72
    "init_win_bytes_fwd",      # 73
    "init_win_bytes_bwd",      # 74
    "act_data_pkt_fwd",        # 75
    "min_seg_size_fwd",        # 76
    "active_mean",             # 77
    "active_std",              # 78
    "active_max",              # 79
    "active_min",              # 80
    "idle_mean",               # 81
    "idle_std",                # 82
    "idle_max",                # 83
    "idle_min",                # 84
    "simillarhttp",            # 85
    "inbound"                  # 86
]